spring.application.name=apache-conusmer-example

# default log level
logging.level.root=INFO

# package-specific override
logging.level.com.srikanth=DEBUG

# console pattern (Logback/Log4j2 compatible)
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
